# Generated by Django 6.1.1 on 2026-09-16 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogs', '0002_alter_category_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dish',
            options={'ordering': ['name'], 'verbose_name': 'Блюдо', 'verbose_name_plural': 'Блюда'},
        ),
        migrations.AddIndex(
            model_name='dish',
            index=models.Index(fields=['slug'], name='catalogs_di_slug_947d66_idx'),
        ),
    ]
